import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { cn } from "@/lib/utils";
import { API_KEY, ENDPOINT, PROJECT_ID } from "@/lib/appwrite.config";

const fontSans = Plus_Jakarta_Sans({
	subsets: ["latin"],
	weight: ["300", "400", "500", "600", "700"],
	variable: "--font-sans",
});
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	console.log("Endpoint:", ENDPOINT);
	console.log("Project ID:", PROJECT_ID);
	console.log("API Key:", API_KEY ? "Loaded" : "Missing");
	return (
		<html lang='en' suppressHydrationWarning>
			<body
				className={cn(
					"min-h-screen bg-dark-300 font-sans antialiased",
					fontSans.variable
				)}
			>
				<ThemeProvider
					attribute='class'
					defaultTheme='dark'
					enableSystem
					disableTransitionOnChange
				>
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
